### ISSUE TITLE
Epsilon value used for testing CIFAR-10

### ISSUE THREAD

**Issue by harsmac** [yjhuangcd/CNNF#1]
Hello, 
Firstly thank you so much for releasing such well written code!! I was wondering in the file `test.py` in line 39, the
` eps = 0.063 `which is roughly equal to 16/255. 
When I evaluate using this I get the same results as the paper. However, in the paper these results are stated for CIFAR10 and eps value of 8/255. Am I missing something?

**Comment by yjhuangcd** [comment]
Thanks for your interest in our work! 
The reason I used eps=16/255 in the code is that, I preprocessed the images to the range of [-1,1] instead of [0,1]. Accordingly, I scaled the perturbation magnitude by 2 to make a fair comparison to the models that are trained on images within [0,1]. Hope that clarifies things:)
